### ISSUE TITLE
element-plus类型缺少加入

### ISSUE THREAD

**Issue by xiaoxian521** [warmthsea/test-volar-types-err#1]
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/44761321/233545088-f0bb3b1d-3129-4d1d-a550-911916b5806c.png">

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/44761321/233544900-1f74529b-bbe7-4134-8b04-baee357793a4.png">

`element-plus/global` 需加入 `compilerOptions` 的 `types` 中才能获得 `Volar` 支持，我用你这个项目将上面的步骤加好并且将 `Vue Language Features (Volar)` 降级到 `v1.2.0` 如上图类型提示是没问题的

<img width="792" alt="image" src="https://user-images.githubusercontent.com/44761321/233545329-af32bf9d-729b-4f81-a354-873a07c0ad4e.png">

**Comment by warmthsea** [comment]
> <img alt="image" width="1273" src="https://user-images.githubusercontent.com/44761321/233545088-f0bb3b1d-3129-4d1d-a550-911916b5806c.png">
> 
> <img alt="image" width="1594" src="https://user-images.githubusercontent.com/44761321/233544900-1f74529b-bbe7-4134-8b04-baee357793a4.png">
> 
> `element-plus/global` 需加入 `compilerOptions` 的 `types` 中才能获得 `Volar` 支持，我用你这个项目将上面的步骤加好并且将 `Vue Language Features (Volar)` 降级到 `v1.2.0` 如上图类型提示是没问题的
> 
> <img alt="image" width="792" src="https://user-images.githubusercontent.com/44761321/233545329-af32bf9d-729b-4f81-a354-873a07c0ad4e.png">

这个复现降低到 1.2的确可以正常使用，但是这个复现是有我原项目删减而来（原项目文件非常多），我同样降低到1.2 后，复现正常（图二），但是原项目出现图中的问题（图一）
![image](https://user-images.githubusercontent.com/45450994/233546193-24878fc0-51c1-47cc-a7ce-ae87d6b8680f.png)
![image](https://user-images.githubusercontent.com/45450994/233546802-0a3aa54c-794a-4f90-a004-4d8200cd5755.png)

**Comment by warmthsea** [comment]
![image](https://user-images.githubusercontent.com/45450994/233558403-5fe86b62-ae65-4a7b-83bb-3394a60e768b.png)
我目前降到了 1.1， 可以正常使用了，thanks
